name: CI Pipeline (Build and test)
on:
  workflow_dispatch:
  pull_request: 
    branches: [ main, WQD1783, base ]
    types: [ opened, reopened, synchronize ]
  push:
    branches: [ main, WQD1783, base ]

jobs:
    assemble:
        runs-on: ubuntu-latest
        env:
            GITHUB_LOGIN: ${{ github.actor }}
            GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        steps:
        -   name: This step creates a copy of the repository for the workflow to run on
            uses: actions/checkout@v3
        -   name: This step sets up java on the machine running this workflow
            uses: actions/setup-java@v3
            with:
                distribution: 'temurin'
                java-version: '16'
            
        -   name: This step assemble the project
            run: |
                chmod +x gradlew        
                ./gradlew assemble
    test:
        runs-on: ubuntu-latest
        needs: assemble
        env:
            GITHUB_LOGIN: ${{ github.actor }}
            GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        steps:
        -   name: This step creates a copy of the repository for the workflow to run on
            uses: actions/checkout@v3
        -   name: This step sets up java on the machine running this workflow
            uses: actions/setup-java@v3
            with:
                distribution: 'temurin'
                java-version: '16'
            
        -   name: This step runs the tests
            run: |
                chmod +x gradlew        
                ./gradlew test


    notify:
        runs-on: ubuntu-latest
        needs: test
        steps:
        -   name: Email notification
            uses: cinotify/github-action@main
            with:
                to: '${{ secrets.TEACHER_EMAIL }}'
                subject: '[Pipeline in ${{ github.repository }}] Workflow for Izabela has been ran successfully.'
                body: 'The assemble and test workflows has been ran successfully.'